const QueryKeys = {
    //common
    // Profile
    FETCH_USER_INFO: "FETCH_USER_INFO",
    GET_COMPANY_DETAILS: "GET_COMPANY_DETAILS",
    //Payments
    FETCH_PLAN_LIST: "FETCH_PLAN_LIST",
    FETCH_SELLER_TYPES: "FETCH_SELLER_TYPES",
    FETCH_REVENUE_LIST: "FETCH_REVENUE_LIST",
    FETCH_SUPPORT_CATEGORY: "FETCH_SUPPORT_CATEGORY",
    FETCH_PAYMENT_LIST: "FETCH_PAYMENT_LIST",
    //billing
    FETCH_INVOICE_LIST: "FETCH_INVOICE_LIST",
    FETCH_ACTIVE_SUBSCRIPTION: "FETCH_ACTIVE_SUBSCRIPTION",
    //Academy
    FETCH_ACADEMY_DETAILS: "FETCH_ACADEMY_DETAILS",
    FETCH_COURSE_DETAILS: "FETCH_COURSE_DETAILS",
};

export default QueryKeys;
